using DevExtreme.AspNet.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;

namespace WidgetGallery.Controllers {

    [Route("api/[controller]/[action]")]
    public class GeoNamesController : Controller {
        static readonly string[] COUNTRIES = new[] {
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "The Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burma",
            "Burundi",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Cape Verde",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Democratic Republic of the Congo",
            "Republic of the Congo",
            "Costa Rica",
            "Ivory Coast",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "East Timor",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "Gabon",
            "The Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Republic of Ireland",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "North Korea",
            "South Korea",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Republic of Macedonia",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Federated States of Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Namibia",
            "Nauru",
            "Nepal",
            "Kingdom of the Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "State of Palestine",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "São Tomé and Príncipe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Swaziland",
            "Sweden",
            "Switzerland",
            "Syria",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Togo",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vatican City",
            "Venezuela",
            "Vietnam",
            "Yemen",
            "Zambia",
            "Zimbabwe"
        };

        static readonly string[] CITIES = new[] {
            "Albuquerque",
            "Anaheim",
            "Anchorage",
            "Arlington",
            "Atlanta",
            "Aurora",
            "Austin",
            "Bakersfield",
            "Baltimore",
            "Baton Rouge",
            "Boise",
            "Boston",
            "Buffalo",
            "Chandler",
            "Charlotte",
            "Chesapeake",
            "Chicago",
            "Chula Vista",
            "Cincinnati",
            "Cleveland",
            "Colorado Springs",
            "Columbus",
            "Corpus Christi",
            "Dallas",
            "Denver",
            "Detroit",
            "Durham",
            "El Paso",
            "Fort Wayne",
            "Fort Worth",
            "Fremont",
            "Fresno",
            "Garland",
            "Gilbert",
            "Glendale",
            "Greensboro",
            "Henderson",
            "Hialeah",
            "Honolulu",
            "Houston",
            "Indianapolis",
            "Irvine",
            "Irving",
            "Jacksonville",
            "Jersey City",
            "Kansas City",
            "Laredo",
            "Las Vegas",
            "Lexington",
            "Lincoln",
            "Long Beach",
            "Los Angeles",
            "Louisville",
            "Lubbock",
            "Madison",
            "Memphis",
            "Mesa",
            "Miami",
            "Milwaukee",
            "Minneapolis",
            "Nashville",
            "New Orleans",
            "New York",
            "Newark",
            "Norfolk",
            "North Las Vegas",
            "Oakland",
            "Oklahoma City",
            "Omaha",
            "Orlando",
            "Philadelphia",
            "Phoenix",
            "Pittsburgh",
            "Plano",
            "Portland",
            "Raleigh",
            "Reno",
            "Richmond",
            "Riverside",
            "Sacramento",
            "Saint Paul",
            "San Antonio",
            "San Diego",
            "San Francisco",
            "San Jose",
            "Santa Ana",
            "Scottsdale",
            "Seattle",
            "St. Louis",
            "St. Petersburg",
            "Stockton",
            "Tampa",
            "Toledo",
            "Tucson",
            "Tulsa",
            "Virginia Beach",
            "Washington",
            "Wichita",
            "Winston–Salem"
        };


        [HttpGet]
        public object Countries(DataSourceLoadOptions loadOptions) {
            return DataSourceLoader.Load(COUNTRIES, loadOptions);
        }

        [HttpGet]
        public object Cities(DataSourceLoadOptions loadOptions) {
            return DataSourceLoader.Load(CITIES, loadOptions);
        }

    }

}
